config/routes.rb
Grouptext::Application.routes.draw do
  
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :phonenumbers
  
  resources :users do
    collection do
      get 'compose_message'
      post 'send_message'
    end
  end
  
  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'users/send_message', :to => 'users#send_message'
  
 

end

app/models/phonenumber.rb
class Phonenumber < ActiveRecord::Base
  
  belongs_to :user
  
  attr_accessible :number, :user_id
  
  number_regex = /^(2|3|4|5|6|7|8|9)\d{9}$/
  
  validates :number, :format     => { :with => number_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :user_id, :presence => true
  #validates_associated :user
  validate :numbers_count
  
  def numbers_count
      if User.find(user_id).phonenumbers.count > 2
         errors.add(:You, "have too many numbers") 
         return true
      else
        return true
      end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :password, :password_confirmation
  
  has_many :phonenumbers, :dependent => :destroy
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
                    
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }
                       
  before_save :encrypt_password
  
  
  
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  class << self
    def authenticate(name, submitted_password)
      user = find_by_name(name)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
 
  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
  
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
    if signed_in?
      @phonenumber=Phonenumber.new
      @phonenumber_items = Phonenumber.where("user_id = ?",current_user.id).paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
end

app/controllers/phonenumbers_controller.rb
class PhonenumbersController < ApplicationController
  before_filter :correct_user
  
  def create
    @phonenumber = current_user.phonenumbers.build(params[:phonenumber])
    if @phonenumber.save
      redirect_to root_path, :flash => {:success => "phonnumber created!"}
    else
      @feed_items = []
      render 'pages/home'
    end
  end

  def destroy
    @phonenumber = Phonenumber.find(params[:id])
    @phonenumber.destroy
    redirect_to root_path, :flash => { :success => "Deleted!" }
  end
  
  private
     def correct_user
        @user = current_user
        redirect_to(root_path) unless current_user?(@user)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:name],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid name/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to root_path
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
require 'twilio-ruby'
require 'rubygems'

class UsersController < ApplicationController
  
  before_filter :correct_user, :only => [:destroy]

  def new
    if signed_in?
      redirect_to root_path
    else
      @user  = User.new
      @title = "Sign up"
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to 'home'
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def send_message
    auth_token = '31b8a6c7fdbc4c1744842089cf77b027'
    account_sid = 'ACe3a9f7035cbf4d299f06c82aedcf3750'
    @client = Twilio::REST::Client.new account_sid, auth_token
    @numbers=current_user.phonenumbers.all
    @message = params[:text]
   
    @numbers.each do |number|
      begin
      @client.account.sms.messages.create(
        :from => '415-599-2671',
        :to => number.number,
        :body => @message
      )
      rescue  
      end
    end
    redirect_to root_path
  end
  
  def compose_message
  end
  
  def destroy
    @user.destroy
    redirect_to users_path, :flash => { :success => "User destroyed." }
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "GroupText"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
  
  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grouptext</title>
<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag 'jquery-1.7.1.js', 'jquery.validate.js', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
	
	<div class = "container">
		<div class="navbar navbar-fixed-top">
		  <div class="navbar-inner">
		    <div class="container">
		      <a class="brand" href="/">GroupText</a>
		      <ul class="nav">
		        <li class="active"><a href="/">Home</a></li>
		        <% if signed_in? %>
				<li><a href="/users/compose_message">Compose Message</a></li>
				<ul class="nav pull-right">
					<li><a href="/signout">Sign Out</a></li>
				</ul>	
				<%end%>
		      </ul>
				<% if !signed_in? %>
					<ul class="nav pull-right">
				      <li><a href="/signin">Sign In</a></li>
				    </ul>	
				<%end%>
		    </div>
		  </div>
		</div>
		
<%= yield %>

</div>

</body>
</html>

app/views/pages/home.html.erb
<% if signed_in? %>
<div class = "row">
	
</div>
  <table class="front" summary="For signed-in users">
    <tr>
        <h1 class="phonenumber">What's up?</h1>
        <%= render 'shared/phonenumber_form' %>
        <%= render 'shared/phonenumbers' %>
      </td>
	
    </tr>
  </table>

<% else %>

<h1>GroupText</h1>
<p>
  This is the home page for GroupText. Sign up or click Sign in to send texts.
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  
<% end %>

app/views/shared/_phonenumber_form.html.erb
<%= form_for @phonenumber do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

	Add a new 10 digit phone number, no hyphens or spaces. Maximum 3.
<div class="row">
	     	
</div>
	<em> 
		<div class = "clearfix">
		<div class="field">
			<%= f.label :number %><br />
    		<%= f.text_field :number %>
  		</div>
  		<div class="actions">
    		<%= f.submit "Submit" %>
  		</div>
		</div>
	</em>
<% end %>

app/views/shared/_phonenumber_item.html.erb
<tr>
  <td class="phonenumber">
    <span class="content"><%= phonenumber_item.number %></span>
  </td>
  <% if current_user?(phonenumber_item.user) %>
    <td>
      <%= link_to "delete", phonenumber_item, :method => :delete,
                                       :confirm => "You sure?",
                                       :title => phonenumber_item.user, :class=> 'btn btn-mini btn-danger' %>
    </td>
  <% end %>
</tr>

app/views/shared/_phonenumbers.html.erb
<%@phonenumber_items = Phonenumber.where("user_id = ?",current_user.id).paginate(:page => params[:page])%>
<% if @phonenumber_items.any? %>
  <table class="table table-striped summary="Number Groups Summary">
	<thead>
		<tr>
			<th> Number </th>
		</tr>
	</thead>
	<tbody>
    <%= render :partial => 'shared/phonenumber_item', :collection => @phonenumber_items %>
  </table>
  <%= will_paginate @phonenumber_items%>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>

app/views/users/_fields.html.erb
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  |
  <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                              :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/compose_message.html.erb
<%=form_tag({:controller => "users", :action => "send_message"}) do%>
	<%= label_tag(:text, "Message Body. Messages over 160 characters will not be sent")%>
	<%= text_area_tag(:text) %>
	<%= submit_tag("Text!") %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>  
<% end %>